// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoBYB8KYX2Y0LC7mTPUeHW78YiUjgHG6o',
    appId: '1:10826962821:web:12d4577b5ca85af0a256ec',
    messagingSenderId: '10826962821',
    projectId: 'kicksy-ca668',
    authDomain: 'kicksy-ca668.firebaseapp.com',
    storageBucket: 'kicksy-ca668.firebasestorage.app',
    measurementId: 'G-YMPP4LW5EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyoc82va_Yoa7x5fFUYuYg3ALRw0w_PpQ',
    appId: '1:10826962821:android:930a148e59b6c23da256ec',
    messagingSenderId: '10826962821',
    projectId: 'kicksy-ca668',
    storageBucket: 'kicksy-ca668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlnXJvUV4JVzSmNvBowFf_9gQq2MfGec',
    appId: '1:10826962821:ios:389a66e272814f8aa256ec',
    messagingSenderId: '10826962821',
    projectId: 'kicksy-ca668',
    storageBucket: 'kicksy-ca668.firebasestorage.app',
    iosBundleId: 'com.example.kicksy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlnXJvUV4JVzSmNvBowFf_9gQq2MfGec',
    appId: '1:10826962821:ios:389a66e272814f8aa256ec',
    messagingSenderId: '10826962821',
    projectId: 'kicksy-ca668',
    storageBucket: 'kicksy-ca668.firebasestorage.app',
    iosBundleId: 'com.example.kicksy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoBYB8KYX2Y0LC7mTPUeHW78YiUjgHG6o',
    appId: '1:10826962821:web:8753de0cd676bcf5a256ec',
    messagingSenderId: '10826962821',
    projectId: 'kicksy-ca668',
    authDomain: 'kicksy-ca668.firebaseapp.com',
    storageBucket: 'kicksy-ca668.firebasestorage.app',
    measurementId: 'G-M0LM9LDJVM',
  );
}
